//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommerciale_EF_TDI2A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public string NumCom { get; set; }
        public string CodeArt { get; set; }
        public Nullable<int> Qte { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
